In [1]:
import numpy as np

A = np.array([[1, 2, 1], [2, 2, 3]])
B = np.array([3, 4, 5])

print(A)
print(B)

[[1 2 1]
 [2 2 3]]
[3 4 5]


In [2]:
# Addition
print(np.add(A, B))

# Subtraction
print(np.subtract(B, A))

# Multiplication
print(np.multiply(A, B))

# Division
print(np.divide(A, B))

[[4 6 6]
 [5 6 8]]
[[2 2 4]
 [1 2 2]]
[[ 3  8  5]
 [ 6  8 15]]
[[0.33333333 0.5        0.2       ]
 [0.66666667 0.5        0.6       ]]


In [3]:
# Power operations
print(np.power(A, 2))

print(np.power(A, B))

[[1 4 1]
 [4 4 9]]
[[  1  16   1]
 [  8  16 243]]
