In [1]:
import numpy as np
arr = np.array([[4, 3, 2],
                [10, 1, 0],
                [5, 8, 24]])
print(arr)

[[ 4  3  2]
 [10  1  0]
 [ 5  8 24]]


In [2]:
# Minimum values
print(np.amin(arr))
print(np.amin(arr, axis=0))
print(np.amin(arr, axis=1))

0
[4 1 0]
[2 0 5]


In [3]:
# Maximum values
print(np.max(arr))
print(np.amax(arr, axis=0))
print(np.amax(arr, axis=1))

24
[10  8 24]
[ 4 10 24]


In [4]:
# Median, Mean, Standard Deviation
print(np.median(arr))
print(np.mean(arr))
print(np.std(arr))

4.0
6.333333333333333
6.944222218666553


In [5]:
arr = np.array([[6, 2, 9],
                [12, 4, 1],
                [7, 15, 20]])
print(arr)

[[ 6  2  9]
 [12  4  1]
 [ 7 15 20]]


In [6]:
# Trigonometric functions with different angles
deg = np.array([15, 45, 75, 120])

print(np.sin(deg*np.pi/180))

print(np.cos(deg*np.pi/180))

print(np.tan(deg*np.pi/180))

[0.25881905 0.70710678 0.96592583 0.8660254 ]
[ 0.96592583  0.70710678  0.25881905 -0.5       ]
[ 0.26794919  1.          3.73205081 -1.73205081]
